### ISSUE TITLE
Support condition on junction table columns

### ISSUE THREAD

**Issue by ivawzh** [graphile-contrib/pg-many-to-many#5]
Say I have tables `a`, `b` and `c`.
`b` is the junction table link between `a` and `c`. 
`b` itself has status `is_active: boolean`.
I need to get all the `c`  associated with `a` through active-only `b`.

Currently, the plugin only accepts argument condition on table `c`. 

Is it possible to achieve what I want? I am also happy to help create PR if you can walk me through some high-level implementation plan.

Cheers

**Comment by mattbretl** [comment]
You can accomplish that without any plugins:

```sql
create table a (
  id serial primary key,
  name text not null
);

create table c (
  id serial primary key,
  name text not null
);

create table b (
  a_id integer not null references a (id),
  c_id integer not null references c (id),
  is_active boolean not null,
  primary key (a_id, c_id)
);

insert into a (id, name) values
  (1, 'a1');

insert into c (id, name) values
  (1, 'c1'),
  (2, 'c2'),
  (3, 'c3');

insert into b (a_id, c_id, is_active) values
  (1, 1, false),
  (1, 2, true),
  (1, 3, true);
```

```
npx postgraphile -c postgres://localhost:5432/db
```

```graphql
{
  allAs {
    nodes {
      bsByAId(condition:{isActive:true}) {
        nodes {
          cByCId {
            id
            name
          }
        }
      }
    }
  }
}
```

```json
{
  "data": {
    "allAs": {
      "nodes": [
        {
          "bsByAId": {
            "nodes": [
              {
                "cByCId": {
                  "id": 2,
                  "name": "c2"
                }
              },
              {
                "cByCId": {
                  "id": 3,
                  "name": "c3"
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

I suppose we could consider adding a `condition` or `filter` argument on the `edges` subfield of the many-to-many connection field, but I suggest just walking the data graph as shown above.

**Comment by ivawzh** [comment]
But that is going to return me duplicated `C`s for `A`, if I have multiple active `B`s linking the same `C` and `A`?

If I am not mistaken, many-to-many `A.Cs` is going to return me the unique set of `C`s?

**Comment by mattbretl** [comment]
You're right. I presumed your junction table had a unique key on the foreign key columns. I don't know why I keep assuming that; see #1. :roll_eyes: 

Thinking about this a bit more now.. `edges` should return all of the matching records in the junction table, while `nodes` should return the matching records in the target table without the "duplicates". (The `edges` field doesn't currently work that way, but that's the plan; see #2.)

For your use case, you want a distinct set of `nodes`. So that brings us back to how to insert the `is_active` condition into a query like this:

```graphql
{
  allAs {
    nodes {
      csByBAIdAndCId {
        nodes {
          id
          name
        }
      }
    }
  }
}
```

I can imagine an overkill solution using the "filtering on related tables" feature of the `filter` plugin, which would allow you do `csByBAIdAndCId(filter:{b:{any:{isActive:{equalTo:true}}}}) {` (translation: return records from `c` that have one or more related records in `b` where `is_active` = `true`). But I haven't published one-to-many relation support in the filter plugin yet, so that's not an option right now.

Have you ruled out using a custom query function for this?

**Comment by ivawzh** [comment]
> Have you ruled out using a custom query function for this?

The many-many junction filter is a very common need for my app. I guess I just want to avoid writing similar code especially database code for this common need. And also, the way I see Postgraphile is almost like an ORM for Graphql. I feel like normally ORM should handle all these common stuff for me. 

> edges should return all of the matching records in the junction table

This is exciting. You are probably helping Relay/Graphql to evolve 🥇 . I am not familiar with Relay myself. Do they already have something for these many-many junction filters?

> `csByBAIdAndCId(filter:{b:{any:{isActive:{equalTo:true}}}})`

Wow, I think I can live with that. Any plan when this will be released?
p.s. it will be really handy if Grpahql allows abstraction for this kind of overwhelming-looking query. Grahpql function? 🤔 

Many thanks for taking care of us 😃 .

**Comment by ivawzh** [comment]
Confirmed the query is beautifully solved by comment above. 
Thanks for all the support. 
Viva la graphile!
